### PR TITLE
added autoplay for youtube

### PR DESCRIPTION
**Pull request by repher**
see https://developers.google.com/youtube/player_parameters?hl=de#autoplay

### CODE REVIEW

**Comment by drmonkeyninja** [comment]
Thanks @repher. Could you just fix the test case that is causing the build to fail before I merge your pull request? :smiley:

**Comment by repher** [comment]
Hello!

ok. there seems to be another error too and some kind of different interpretation of allowfullscreen. on my system is results in  allowfullscreen=“allowfullscreen”. I adapted the tests. also for vimeo. also i changed some settings ...

Hope this is ok.

Bernhard

**Comment by drmonkeyninja** [comment]
Thanks @repher.

**Comment by repher** [comment]
you are welcome .. if i have some spare time i will add some options to youtube …

Bernhard

**Pull request merged**
